# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Professional changelog management CLI for SemVer projects"
  homepage "https://github.com/peiman/changie"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiman/changie/releases/download/v1.0.0/changie_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "7386f04c4c57811b9139b3d800bc2a44dca90fcb18f7f0845e565089bdd49816"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiman/changie/releases/download/v1.0.0/changie_1.0.0_Darwin_arm64.tar.gz"
      sha256 "9887db8d9f3b8a1a8410756db05bec43d710a134e5edc71e11f3bb428ee69ff0"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.0/changie_1.0.0_Linux_x86_64.tar.gz"
      sha256 "8f8e87f7b02fd401cb949470a86452e60660e230c33e3886889bc48c16f9a37c"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.0/changie_1.0.0_Linux_armv6.tar.gz"
      sha256 "0a99ba342387b8e8155290f786b72bc9c800a731ec491b28a8051fa52e30681a"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.0/changie_1.0.0_Linux_arm64.tar.gz"
      sha256 "3dd242999ba5b05019c62d8ee3d535b3cd5699497f2c617131c819eb03a4a32e"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  test do
    system "#{bin}/changie", "version"
  end
end
