# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Professional changelog management CLI for SemVer projects"
  homepage "https://github.com/peiman/changie"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiman/changie/releases/download/v1.0.2/changie_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "312ecc71be7cd155490f25b2cb5d5ce649d0b72e02d331a2806395fc76795655"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiman/changie/releases/download/v1.0.2/changie_1.0.2_Darwin_arm64.tar.gz"
      sha256 "727be1b338e33bfbf001e3816b3b1ce724054c389b74a3ef18acafaf42b203e0"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.2/changie_1.0.2_Linux_x86_64.tar.gz"
      sha256 "e754f1a87ea44cc5c6c2f6cf5eb704d513f4947928fa06b321cdb456d6dd3628"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.2/changie_1.0.2_Linux_armv6.tar.gz"
      sha256 "13993ef43b338a19ad7015e01b9bd8ad30f2c6a5cd56fa553f3f29826c16d701"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.0.2/changie_1.0.2_Linux_arm64.tar.gz"
      sha256 "8957d7dbfdfeaee18298724a976b14878dab4c068712ff15ace615e15dfa16e7"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  test do
    system "#{bin}/changie", "version"
  end
end
