# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changie < Formula
  desc "Professional changelog management CLI for SemVer projects"
  homepage "https://github.com/peiman/changie"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiman/changie/releases/download/v1.1.0/changie_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "f5dd65ecc04a20fccfb8fc590caec426d5e2e9a58d56fee2b205a8c32299a9f7"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiman/changie/releases/download/v1.1.0/changie_1.1.0_Darwin_arm64.tar.gz"
      sha256 "d969295a2b7431ed5de18da132afb469308cf33766e26c85a91cee42b7fc08a3"

      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.1.0/changie_1.1.0_Linux_x86_64.tar.gz"
      sha256 "34bf2f9dbf1be38cb869d8486a2c903902fc3be565ccbaba4fffe5ad1844b423"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.1.0/changie_1.1.0_Linux_armv6.tar.gz"
      sha256 "e1800e94760c1d069f1172d8f33a497fb481ed2deaf0dc135b912c88e5cd139c"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiman/changie/releases/download/v1.1.0/changie_1.1.0_Linux_arm64.tar.gz"
      sha256 "afb9203251e0d9d85f63f60ce8094bc322280ebd4e986db4d991e7230ad4b9b9"
      def install
        bin.install "changie"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"changie", "completion")
      end
    end
  end

  test do
    system "#{bin}/changie", "version"
  end
end
